# Generated by Django 3.2.6 on 2021-10-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],), 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
